### ISSUE TITLE
is it compatible with django 3.0?  or did i do something wrong?

### ISSUE THREAD

**Issue by JudiPuak** [monim67/django-bootstrap-datepicker-plus#45]
hello all

**Describe the bug**
Apparently it is not compatible with django 3.0
It gives an error:  TypeError: render() got an unexpected keyword argument 'renderer'

**To Reproduce**
**Expected behavior**
I was hoping that it would work with django 3.0 like it does with django 2.0.5

**Screenshots**

**Setup Information (please complete the following information):**
 - OS: Win 8.1 32-bit
 - Browser Firefox Brave
 - Browser version Firefox 75.0 / Brave 1.8.95
 - Python version 3.7.3
 - Django version 3.0.5
 - Bootstrap version 4
 - jQuery version django-jquery 3.1.0

[x] I have followed the [configuration instructions][configuration_page] and checked out the
[common error troubleshooting][troubleshooting_page] page.

[configuration_page]: https://monim67.github.io/django-bootstrap-datepicker-plus/configure/
[troubleshooting_page]: https://django-bootstrap-datepicker-plus.readthedocs.io/en/latest/Troubleshooting.html

could you / someone please help me?
perhaps I do something wrong?
right now in dev, i use a workaround:  i comment out line 96 of django/forms/boundfield.py
(renderer=self.form.renderer,)
but when using heroku, i can't access the installed site-packages

or perhaps you could release an update to work with django 3.0?

thank you so much

jud

**Comment by christianwgd** [comment]
Hi, since i'm using this in different projects with django 3, from my perspective you have another problem.

**Comment by JudiPuak** [comment]
hi christian

yes
after further investigation, the culprit is django-smart-selects

my bad.  i am sorry.
